# Generated by Django 5.2 on 2025-05-11 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='VersionApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_version', models.CharField(max_length=20)),
                ('descripcion_cambios', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'versiones_api',
            },
        ),
        migrations.RemoveField(
            model_name='api',
            name='version',
        ),
        migrations.RemoveField(
            model_name='api',
            name='visibilidad',
        ),
        migrations.AddField(
            model_name='api',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='api',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='api',
            name='detalles_tecnicos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api',
            name='documentacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='api',
            name='estado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='api',
            name='permiso',
            field=models.CharField(choices=[('publico', 'Público'), ('privado', 'Privado'), ('restringido', 'Restringido')], default='privado', max_length=12),
        ),
        migrations.AlterField(
            model_name='api',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelTable(
            name='api',
            table='apis',
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=100, unique=True)),
                ('contrasena_hash', models.TextField()),
                ('nombres', models.CharField(blank=True, max_length=100, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True, null=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True, null=True)),
                ('rol', models.ForeignKey(blank=True, db_column='rol_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.rol')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_sesion', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True, null=True)),
                ('expira_en', models.DateTimeField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(blank=True, db_column='usuario_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.usuario')),
            ],
            options={
                'db_table': 'sesiones',
            },
        ),
        migrations.CreateModel(
            name='PermisoApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, null=True)),
                ('api', models.ForeignKey(blank=True, db_column='api_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.api')),
                ('usuario', models.ForeignKey(blank=True, db_column='usuario_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.usuario')),
            ],
            options={
                'db_table': 'permisos_api',
            },
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=100)),
                ('tabla_afectada', models.CharField(blank=True, max_length=100, null=True)),
                ('registro_id', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('detalles', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, db_column='usuario_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.usuario')),
            ],
            options={
                'db_table': 'auditoria',
            },
        ),
        migrations.AddField(
            model_name='api',
            name='creado_por',
            field=models.ForeignKey(blank=True, db_column='creado_por', null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.usuario'),
        ),
        migrations.AddIndex(
            model_name='api',
            index=models.Index(fields=['nombre'], name='idx_api_nombre'),
        ),
        migrations.AddField(
            model_name='versionapi',
            name='api',
            field=models.ForeignKey(blank=True, db_column='api_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.api'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['correo'], name='idx_usuario_correo'),
        ),
        migrations.AddIndex(
            model_name='sesion',
            index=models.Index(fields=['token_sesion'], name='idx_sesion_token'),
        ),
        migrations.AlterUniqueTogether(
            name='permisoapi',
            unique_together={('api', 'usuario')},
        ),
        migrations.AddIndex(
            model_name='auditoria',
            index=models.Index(fields=['accion'], name='idx_auditoria_accion'),
        ),
        migrations.AddIndex(
            model_name='auditoria',
            index=models.Index(fields=['timestamp'], name='idx_auditoria_fecha'),
        ),
        migrations.AddIndex(
            model_name='versionapi',
            index=models.Index(fields=['numero_version'], name='idx_versiones_version'),
        ),
        migrations.AlterUniqueTogether(
            name='versionapi',
            unique_together={('api', 'numero_version')},
        ),
    ]
