# Generated by Django 5.2 on 2025-05-17 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_usuario_biografia_usuario_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(max_length=160),
        ),
    ]
