# Generated by Django 5.2 on 2025-05-20 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_alter_usuario_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'subcategoria',
            },
        ),
        migrations.CreateModel(
            name='Tematica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tematica',
            },
        ),
        migrations.AddField(
            model_name='api',
            name='id_categoria',
            field=models.ForeignKey(blank=True, db_column='id_categoria', null=True, on_delete=django.db.models.deletion.SET_NULL, to='apis.categoria'),
        ),
        migrations.AddField(
            model_name='api',
            name='id_subcategoria',
            field=models.ForeignKey(blank=True, db_column='id_subcategoria', null=True, on_delete=django.db.models.deletion.SET_NULL, to='apis.subcategoria'),
        ),
        migrations.AddField(
            model_name='api',
            name='id_tematica',
            field=models.ForeignKey(blank=True, db_column='id_tematica', null=True, on_delete=django.db.models.deletion.SET_NULL, to='apis.tematica'),
        ),
        migrations.CreateModel(
            name='MetodoApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE'), ('PATCH', 'PATCH')], max_length=6)),
                ('endpoint', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('lenguaje_codigo', models.CharField(blank=True, max_length=50, null=True)),
                ('codigo', models.TextField(blank=True, null=True)),
                ('parametros', models.JSONField(blank=True, null=True)),
                ('retorno', models.JSONField(blank=True, null=True)),
                ('api', models.ForeignKey(blank=True, db_column='api_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.api')),
            ],
            options={
                'db_table': 'metodos_api',
                'constraints': [models.CheckConstraint(condition=models.Q(('metodo__in', ['GET', 'POST', 'PUT', 'DELETE', 'PATCH'])), name='chk_metodo_valid')],
            },
        ),
    ]
