# Generated by Django 5.2 on 2025-05-28 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_categoria_subcategoria_tematica_api_id_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='origen',
            field=models.CharField(default='local', max_length=20),
        ),
    ]
