# Generated by Django 5.2 on 2025-06-10 00:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0008_usuario_origen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Mantener opciones de modelo
        migrations.AlterModelOptions(
            name='permisoapi',
            options={'ordering': ['-creado_en']},
        ),
        # Agregar campo colaborador antes de alterar restricción
        migrations.AddField(
            model_name='permisoapi',
            name='colaborador',
            field=models.ForeignKey(
                blank=True,
                db_column='colaborador_id',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        # Ahora alterar unique_together incluyendo colaborador
        migrations.AlterUniqueTogether(
            name='permisoapi',
            unique_together={('api', 'colaborador')},
        ),
        # Agregar relación ManyToMany en API
        migrations.AddField(
            model_name='api',
            name='colaboradores',
            field=models.ManyToManyField(
                related_name='apis_colaborando',
                through='apis.PermisoApi',
                to=settings.AUTH_USER_MODEL
            ),
        ),
        # Ajustar id y tabla
        migrations.AlterField(
            model_name='permisoapi',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='permisoapi',
            table='permiso_api',
        ),
        # Eliminar campo usuario obsoleto
        migrations.RemoveField(
            model_name='permisoapi',
            name='usuario',
        ),
    ]
