# Generated by Django 5.2 on 2025-06-11 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0009_alter_permisoapi_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='colaboradores',
            field=models.ManyToManyField(related_name='apis_colaborando', through='apis.PermisoApi', to='apis.usuario'),
        ),
        migrations.AlterField(
            model_name='permisoapi',
            name='colaborador',
            field=models.ForeignKey(blank=True, db_column='colaborador_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.usuario'),
        ),
    ]
