# Generated by Django 5.2.1 on 2025-05-16 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_rol_versionapi_remove_api_version_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='api',
            constraint=models.UniqueConstraint(fields=('nombre', 'creado_por'), name='unique_api_por_usuario'),
        ),
    ]
